事業をエンジニアリングしよう ②実装
sh0327akg/mokumoku pull request #2
Opened 2022-12-01 09:51 UTC by sh0327akg

### 卒業試験

以下の実装方針を基に実装しました。
【実装方針】
- ログイン後、HobbyとProfileを登録できる
- 他のユーザーのHobbyとProfileを閲覧できる。
- 他のユーザーをフォローできるし、フォロー解除することもできる。

【注意点】
- usersテーブルに"profile"・"hobby"カラムを追加する。
- フォロー・アンフォローするボタンは"フォローする"・"フォローを外す"とする。

ご確認のほどよろしくお願いいたします。

2022-12-01 09:51 UTC, sh0327akg commented
[![Image from Gyazo](https://i.gyazo.com/8574d7864028ff42c848abab27dad3ed.png)](https://gyazo.com/8574d7864028ff42c848abab27dad3ed)

2022-12-01 10:57 UTC, busitora requested changes
謎の差分?(images ) もpush されていますが、今回はOKとしますが、今後ご注意ください！

こめんとしました！

2022-12-01 10:57 UTC, busitora commented on app/models/user.rb
> +  has_many :followeres, through: :reverse_of_relationships, source: :follower
```suggestion
  has_many :followers, through: :reverse_of_relationships, source: :follower
```
ではないでしょうか? 全体置換で直してくださると 👍

2022-12-01 10:57 UTC, busitora commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
存在しない場合は return し 存在する場合のみ destroy するようにすると good です！

一度 コンソールにて、 nil に対して 

`User.unfollow(nil)..destroy`

してみてください！どうなりますか？結果もスクリーンショットor コードで共有お願いします！！

2022-12-01 10:57 UTC, busitora commented on app/views/users/show.html.erb
> +            <%if @user != current_user%>
ここ 可能なら model メソッドで定義したいですね

2022-12-01 12:41 UTC, sh0327akg commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
[![Image from Gyazo](https://i.gyazo.com/e48296230181c3a5e01f0ef2109cf8c1.png)](https://gyazo.com/e48296230181c3a5e01f0ef2109cf8c1)
上記の通りスクリーンショット共有します。

2022-12-01 13:18 UTC, sh0327akg commented on app/models/user.rb
> +  has_many :followeres, through: :reverse_of_relationships, source: :follower
ご指摘ありがとうございます。
修正しました。

2022-12-01 13:20 UTC, sh0327akg commented on app/views/users/show.html.erb
> +            <%if @user != current_user%>
modelでどう定義して良いのかがわかりませんでした。
モデルでcurrent_userが使えないので、使わない方法を模索しましたのですがわかりませんでした。

2022-12-01 13:21 UTC, sh0327akg commented
上記の通りコメントにリプライしましたのでお手数ですがご確認のほどよろしくお願いします。

2022-12-01 22:02 UTC, sh0327akg commented on app/views/users/show.html.erb
> +            <%if @user != current_user%>
すみません！
適当なメソッド名が思いつきませんでしたが実装できました。

2022-12-02 00:17 UTC, Tsuchiya2 commented
今後は1つのコメントに対して修正を行う際は1コミットを心がけましょう。
[ee977d3](https://github.com/sh0327akg/mokumoku/pull/2/commits/ee977d3e60baab2d73f31ead09f71686c9f4b654) ←で変更履歴を確認する際にレビュワーが対象箇所を探すのにも負担になるので、その辺りも意識していきましょう。

2022-12-02 00:24 UTC, Tsuchiya2 reviewed
コメントしました。（先程指摘したコミットを意識して、どのコミットがどのコメントに対するものなのか回答コメントに記載してみましょう。）

2022-12-02 00:24 UTC, Tsuchiya2 commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
rubocopを一度実行してみましょうか。確かreturnの後は空行を入れるように指摘されるかと思うので確認をお願いします。

2022-12-02 02:32 UTC, sh0327akg commented
> コメントしました。（先程指摘したコミットを意識して、どのコミットがどのコメントに対するものなのか回答コメントに記載してみましょう。）
[2c9a5c9](https://github.com/sh0327akg/mokumoku/pull/2/commits/2c9a5c9255cf62f44f37277b55a19cb8fd4a89e9)←こちらでrubocop指摘箇所を修正しました。

2022-12-02 02:34 UTC, sh0327akg commented on app/views/users/show.html.erb
> +            <%if @user != current_user%>
[ee977d3](https://github.com/sh0327akg/mokumoku/pull/2/commits/ee977d3e60baab2d73f31ead09f71686c9f4b654)←
こちらのコミットでモデルメソッドを追加しています。

2022-12-02 02:35 UTC, sh0327akg commented on app/models/user.rb
> +  has_many :followeres, through: :reverse_of_relationships, source: :follower
[090bca5](https://github.com/sh0327akg/mokumoku/pull/2/commits/090bca5b89aadcf75312d6a3528aa74372a1ea77)←こちらのコミットでfollowersに修正しています。

2022-12-02 02:36 UTC, sh0327akg commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
[2c9a5c9](https://github.com/sh0327akg/mokumoku/pull/2/commits/2c9a5c9255cf62f44f37277b55a19cb8fd4a89e9)←こちらでrubocop指摘箇所を修正しました。

2022-12-03 01:46 UTC, murata0705 commented
良いと思います 👍🏻 
マージして次の課題に進みましょう。

2022-12-03 09:24 UTC, merged